# Generated by Django 5.0.6 on 2024-11-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_commande_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="contacte",
        ),
        migrations.AddField(
            model_name="commande",
            name="zipcode",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
